name: React Otomatik Build ve Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Kodları Çek
      uses: actions/checkout@v3

    - name: Node.js Kurulumu
      uses: actions/setup-node@v3
      with:
        node-version: 22 # Projenin kullandığı Node versiyonuna göre değiştirebilirsin

    - name: Bağımlılıkları Yükle
      run: npm install --legacy-peer-deps

    - name: Projeyi Derle (Build)
      run: npm run build

    - name: Dosyaları Sunucuya Gönder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 94.73.147.156
        username: u2680154
        password: ${{ secrets.FTP_PASSWORD }}
        # ÖNEMLİ: Sadece build klasörünün içindekileri gönderiyoruz
        local-dir: ./dist/public/ 
        server-dir: public_html/